# Generated by Django 3.1.6 on 2021-02-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100, verbose_name='API adress or URL')),
                ('url', models.CharField(max_length=100, verbose_name='URL')),
                ('continent', models.CharField(blank=True, max_length=150, verbose_name='Continent')),
                ('country', models.CharField(blank=True, max_length=150, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=150, verbose_name='City')),
                ('latitude', models.FloatField(blank=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'GeoLocation',
                'verbose_name_plural': 'GeoLocations',
            },
        ),
    ]
