# Generated by Django 3.1.6 on 2021-02-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='url',
            field=models.CharField(blank=True, max_length=100, verbose_name='URL'),
        ),
    ]
