# Generated by Django 3.1.6 on 2021-02-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210211_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='URL'),
        ),
    ]
